number_worker: 5
page_per_job: 1
regular:
  home_page: !ruby/regexp /／[^／]*ｉｎｄｅｘ(.*)．(ａｓｐ|ｓ?ｈｔｍｌ?|ｐｈｐ)$/
  address:
    multiple: 
      a: !ruby/regexp /^〒(.*?)\s?／?\s?〒.*/
      b: !ruby/regexp /^[\[＜【].*本?社?[】＞\]](.*?)\s?／?\s?[\[＜【].*[】＞\]].*/
      c: !ruby/regexp /^.+：(.*)\/.*：/
      d: !ruby/regexp /^(〒[０-９0-9]+[－-][０-９0-9]+\s?+(〒[０-９0-9]+[－‐][０-９0-9]+\s?)+.*)/
      e: !ruby/regexp /^〒?(\s?[０-９0-9[-－‐]{1}]{8}\s*[\p{Hiragana}\p{Katakana}\p{Han}[／]]+[^〒]+)\s*[^〒]*/
    # address1and2: !ruby/regexp /^〒?([\d-]*)?(.+?[都|道|府|県])?(.+?[市|区|町|村])?(.*)$/
    # address1and2: !ruby/regexp /^〒?([\d-]*)?(.+?[都|道|府|県])?(.+?[市|区|町|村])?(.*)$/
    address1and2: !ruby/regexp /^〒?([０-９0-9[-－‐]{1}]{8}\s*[〒?[０-９0-9[-－‐]{1}]{8}\s*]*)?
                  (.+?[都|道|府|県])?(.+?[市|区|町|村])?(.*)$/x
    address3and4: !ruby/regexp /^(\W+[０-９0-9一-十]+\D+[０-９0-9一-十][[−－-][０-９0-9一-十]]*番?地?\d*号?
      |\W+[0-9０-９一-十]?+丁目[0-9０-９一-十]+\s*番?地?[0-9０-９一-十]+号
      |.*[0-9０-９一-十]+丁目[[−－-]?[0-9０-９一-十]]+番?地?の?\d*
      |\W+[0-9０-９一-十]?+町\s?[[−－-]?[０-９0-9一-十]]+番?地?[0-9０-９一-十]+番?地?号?
      |\W*\S?*\s+[０-９0-9一-十]?[[−－-][０-９0-9一-十]]*番?地?\s+
      |\W*[０-９0-9一-十]?[[−－-][０-９0-9一-十]]*番?地?\d*号?\s?)?\s*
      ([\(（【]本[社店部][】）\)]|[\(（【]総合受付[】）\)])?(.*)$/x
    address34exception: !ruby/regexp /^(\W+[０-９0-9一-十]+[[−－-][０-９0-9一-十]]*[−－-][０-９0-9一-十]+)\D(\d+F+.*)/
    address4:
      end_string: !ruby/regexp /(.*)([\(（【].*[本支][社店部][】）\)]|[\(（【]総合受付[】）\)]|／[本支][社店部]|／)$/
      bracket: !ruby/regexp /^（?(.*?)[（【\(＜\[](.*)[】＞\)）\]](.*)/
  postal_code: !ruby/regexp /〒?([０-９0-9[-－‐]{1}]{8}\s?)/
export_file:
  company_id: "企業ID"
  postal_code: "郵便番号"
  address1: "都道府県"
  address2and3: "市区町村番地"
  address4: "ビル名"
  today:
    text: "取得日"
    format: "%Y/%m/%d"
  tel: "電話番号"
  job:
    sheet: "Job"
    no: "NO"
    id: "求人ID"
    source: "掲載媒体"
    url: "掲載URL"
    title: "案件タイトル"
    inexperience:
      text: "未経験OK"
      ok: "◯"
    job_category: "募集職種"
    holiday: "休日、休暇"
  company:
    sheet: "Company"
mechanize:
  requirement: "対象となる方"
  treatment: "待遇・福利厚生"
  holiday: "休日・休暇"
  full_tel: "連絡先"
  home_page: "企業HP"
  establishment: "設立"
  employees_number: "従業員数"
  capital: "資本金"
  sales: "売上高"
  job_category: "職種"
  job_type: "職種名"
  salary: "想定年収（給与詳細）"
company_name: "企業名"
content: "仕事内容"
work_time: "勤務時間"
salary: "給与"
workplace: "勤務地"
business_category: "業種"
requirement: "応募資格"
job_category: "募集職種"
treatment: "待遇"
space: " 　"
html:
  br: "br"
  p: "p"
  n: "\n"
strange: "　＋ー、。,.･－‐．～：！※＆"
bracket: "【】（）「」／＜＞()，≪≫［］『』"
option_crawler: [["Green", "green"], ["Doda", "doda"], ["Ecareer", "ecareer"], ["J-sen", "jsen"]]
crawler:
  full_address: "本社所在地"
  green:
    url: "http://www.green-japan.com"
    link_text: "求人を探す"
    holiday: "休日/休暇"
    company_name: "会社名"
    business_category: "業界"
    sales: "売上（3年分）"
    establishment: "設立年月"
    address: "勤務地詳細"
  jsen:
    url: "http://job.j-sen.jp"
    full_address: "事業所"
  doda:
    url: "http://doda.jp/"
    click: "求人検索"
    experience: "未経験歓迎"
    detail_text: "募集要項"
  ecareer:
    url: "http://www.ecareer.ne.jp"
    job_content: "具体的な業務内容"
    requirement:
      part1: "年齢"
      part2: "学歴"
      part3: "必須の経験スキル・資格"
    treatment: "諸手当"