number_worker: 10
page_per_job: 1
download_path: "public/uploads/"
regular:
  home_page: !ruby/regexp /／[^／]*ｉｎｄｅｘ(.*)．(ａｓｐ|ｓ?ｈｔｍｌ?|ｐｈｐ)$/
  address:
    multiple: 
      a: !ruby/regexp /^〒(.*?)\s?／?\s?〒.*/
      b: !ruby/regexp /^[\[＜【].*本?社?[】＞\]](.*?)\s?／?\s?[\[＜【].*[】＞\]].*/
      c: !ruby/regexp /^.+：(.*)\/.*：/
      d: !ruby/regexp /^(〒[０-９\d]+[－-][０-９\d]+\s?+(〒[０-９\d]+[－‐][０-９\d]+\s?)+.*)/
      e: !ruby/regexp /^〒?(\s?[０-９\d[-－‐]{1}]{8}\s*[\p{Hiragana}\p{Katakana}\p{Han}[／]]+[^〒]+)\s*[^〒]*/
    # address1and2: !ruby/regexp /^〒?([\d-]*)?(.+?[都|道|府|県])?(.+?[市|区|町|村])?(.*)$/
    # address1and2: !ruby/regexp /^〒?([\d-]*)?(.+?[都|道|府|県])?(.+?[市|区|町|村])?(.*)$/
    total: !ruby/regexp /〒?([０-９\d[-－‐]{1}]{8}\s*[〒?[０-９\d[-－‐]{1}]{8}\s*]*)?
      (.+?[都|道|府|県])?(.+?[市|区|町|村])?
      (\W+[０-９\d一二三四五六七八九十]+\D+[０-９\d一二三四五六七八九十][[−－-][０-９\d一二三四五六七八九十]\s?]*番?地?\d*号?
        |\W+[０-９\d一二三四五六七八九十]?+丁目[０-９\d一二三四五六七八九十]+\s*番?地?[０-９\d一二三四五六七八九十]+号
        |.*[０-９\d一二三四五六七八九十]+丁目[[−－-]?[０-９\d一二三四五六七八九十]]+番?地?の?\d*
        |\S*[０-９\d一二三四五六七八九十]?[[−－-][０-９\d一二三四五六七八九十]]*番?地?\d*号?\s?
        |\W+[０-９\d一二三四五六七八九十]?+町\s?[[−－-]?[０-９\d一二三四五六七八九十]]+番?地?[０-９\d一二三四五六七八九十]+番?地?号?
        |\W*\S?*\s+[０-９\d一二三四五六七八九十]?[[−－-][０-９\d一二三四五六七八九十]]*番?地?\s+
        |\W*[０-９\d一二三四五六七八九十]?[[−－-][０-９\d一二三四五六七八九十]]*番?地?\d*号?\s?)?\s*
      ([^※【\n]*)/x

    address1and2: !ruby/regexp /^〒?([０-９\d[-－‐]{1}]{8}\s*[〒?[０-９\d[-－‐]{1}]{8}\s*]*)?
                  (.+?[都|道|府|県])?(.+?[市|区|町|村])?(.*)$/x
    address3and4: !ruby/regexp /^(\W+[０-９\d一二三四五六七八九十]+\D+[０-９\d一二三四五六七八九十][[−－-][０-９\d一二三四五六七八九十]]*番?地?\d*号?
      |\W+[０-９\d一二三四五六七八九十]?+丁目[０-９\d一二三四五六七八九十]+\s*番?地?[０-９\d一二三四五六七八九十]+号
      |.*[０-９\d一二三四五六七八九十]+丁目[[−－-]?[０-９\d一二三四五六七八九十]]+番?地?の?\d*
      |\W+[０-９\d一二三四五六七八九十]?+町\s?[[−－-]?[０-９\d一二三四五六七八九十]]+番?地?[０-９\d一二三四五六七八九十]+番?地?号?
      |\W*\S?*\s+[０-９\d一二三四五六七八九十]?[[−－-][０-９\d一二三四五六七八九十]]*番?地?\s+
      |\W*[０-９\d一二三四五六七八九十]?[[−－-][０-９\d一二三四五六七八九十]]*番?地?\d*号?\s?)?\s*
      ([\(（【]本[社店部][】）\)]|[\(（【]総合受付[】）\)])?(.*)$/x
    address34exception: !ruby/regexp /^(\W+[０-９\d一二三四五六七八九十]+[[−－-][０-９\d一二三四五六七八九十]]*[−－-][０-９\d一二三四五六七八九十]+)\D(\d+F+.*)/
    address4:
      end_string: !ruby/regexp /(.*)([\(（【].*[本支][社店部][】）\)]|[\(（【]総合受付[】）\)]|／[本支][社店部]|／)$/
      bracket: !ruby/regexp /^（?(.*?)[（【\(＜\[](.*)[】＞\)）\]](.*)/
  postal_code: !ruby/regexp /〒?([０-９\d[-－‐]{1}]{8}\s?)/
export_file:
  company_id: "企業ID"
  postal_code: "郵便番号"
  address1: "都道府県"
  address2and3: "市区町村番地"
  address4: "ビル名"
  today:
    text: "取得日"
    format: "%Y/%m/%d"
  tel: "電話番号"
  job:
    sheet: "Job"
    no: "NO"
    id: "求人ID"
    source: "掲載媒体"
    url: "掲載URL"
    title: "案件タイトル"
    inexperience:
      text: "未経験OK"
      ok: "◯"
    job_category: "募集職種"
    holiday: "休日、休暇"
  company:
    sheet: "Company"
mechanize:
  requirement: "対象となる方"
  treatment: "待遇・福利厚生"
  holiday: "休日・休暇"
  full_tel: "連絡先"
  home_page: "企業HP"
  establishment: "設立"
  employees_number: "従業員数"
  capital: "資本金"
  sales: "売上高"
  job_category: "職種"
  job_type: "職種名"
  salary: "想定年収（給与詳細）"
company_name: "企業名"
convert_name: "名寄せ用企業名"
content: "仕事内容"
work_time: "勤務時間"
salary: "給与"
workplace: "勤務地"
business_category: "業種"
requirement: "応募資格"
job_category: "募集職種"
treatment: "待遇"
space: " 　"
html:
  br: "br"
  p: "p"
  n: "\n"
strange: "　＋ー、。，,.･－‐．～：！※＆"
job_strange: "　＋ー、。，,.･－‐．～：！※＆／・()【】『』「」（）≪≫＜＞[]＼％★◆◎’［”］“■"
bracket: "【】（）「」／＜＞()，≪≫［］『』"
option_crawler: [["Green", "green"], ["Doda", "doda"], ["Ecareer", "ecareer"], ["J-sen", "jsen"]]
crawler:
  full_address: "本社所在地"
  green:
    url: "http://www.green-japan.com"
    link_text: "求人を探す"
    holiday: "休日/休暇"
    company_name: "会社名"
    business_category: "業界"
    sales: "売上（3年分）"
    establishment: "設立年月"
    address: "勤務地詳細"
  jsen:
    url: "http://job.j-sen.jp"
    new_address: "事業所"
    old_address: "所在地"
    workplace: "住所"
  doda:
    url: "http://doda.jp/"
    click: "求人検索"
    experience: "未経験歓迎"
    detail_text: "募集要項"
  ecareer:
    url: "http://www.ecareer.ne.jp"
    job_content: "具体的な業務内容"
    requirement:
      part1: "年齢"
      part2: "学歴"
      part3: "必須の経験スキル・資格"
    treatment: "諸手当"
list_proxy:
  - ["113.255.129.42", "80"]
  - ["92.48.127.95", "3128"]
  - ["111.161.126.99", "80"]
  - ["221.208.194.108", "80"]
  - ["62.201.200.14", "80"]
  - ["223.19.230.181", "80"]
  - ["124.240.187.77", "843"]
  - ["183.178.98.88", "8080"]
  - ["188.165.141.151", "80"]
  - ["112.25.41.136", "80"]
  - ["59.127.154.78", "80"]
  - ["113.215.0.130", "80"]
  - ["120.203.159.14", "8118"]
  - ["37.204.50.170", "80"]
  - ["213.201.83.248", "80"]
  - ["187.49.92.34", "6006"]
  - ["60.13.74.184", "843"]
  - ["124.240.187.88", "80"]
  - ["86.100.118.44", "80"]
  - ["211.141.82.247", "8118"]
  - ["124.240.187.76", "81"]
  - ["95.128.246.10 8080"]
  - ["211.137.39.21", "80"]
  - ["211.137.39.20", "8080"]
  - ["89.212.49.215", "80"]
  - ["219.142.192.196", "1238"]
  - ["186.148.5.8", "80"]
  - ["173.192.79.55", "80"]
  - ["117.136.234.9", "80"]
  - ["124.240.187.79", "80"]
  - ["117.136.234.10", "843"]
  - ["117.136.234.7", "843"]
  - ["117.136.234.6", "843"]
  - ["117.136.234.18", "843"]
  - ["117.136.234.3", "82"]
  - ["190.63.140.71", "80"]
  - ["1.180.163.188", "80"]
  - ["213.239.214.73", "2358"]
  # - ["124.240.187.76", "83"]
  # - ["113.252.178.246", "80"]
    # - ["58.96.182.48", "8090"]
    # - ["61.235.249.222", "80"]
    # - ["50.240.46.244", "7004"]
  # - ["46.139.223.182", "80"]
  # - ["84.29.245.44", "80"]
  # - ["118.193.155.37", "808"]
    # - ["202.108.35.151", "800"]
    # - ["113.215.0.130", "843"]
  # - ["124.240.187.89", "80"]
   # - ["124.240.187.84", "83"]
   # - ["124.240.187.89", "843"]
     # - ["62.194.188.79", "80"]
       # - ["62.45.108.101", "80"]
         # - ["213.85.92.10", "80"]
           # - ["124.240.187.81", "80"]
             # - ["213.136.79.124", "80"]
               # - ["94.225.49.208", "80"]
