default: &default
  adapter: mysql2
  encoding: utf8
  pool: 25
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: tmdoda_development
  pool: 25

test: &test
  <<: *default
  database: db/test.mysql2tmdoda

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>

cucumber:
  <<: *test
